### ISSUE TITLE
insufficient balance to pay for gas

### ISSUE THREAD

**Issue by alphaqiu** [mosaicnetworks/monetd#5]
**Expected behaviour**
Can return correctly when calling these interfaces：
poa whitelist
poa check

In fact, I don't know how much gas it takes to execute such a call. Although this is a project of `evm-lite-cli`, it actually calls `evm-lite` started by `monetd`. So submit a question here.

**Actual behaviour**

evmlc$ poa whitelist
**insufficient balance to pay for gas**

evmlc$ p c
? Nominee address:  0x8a8eade219c8e6a7a813c488e76937d0bf84d5d6
**insufficient balance to pay for gas**

**Comment by arrivets** [comment]
Thanks,
I'll look into it.
In the meantime, please try setting the gas price to 0 on your transaction.
I am not sure why, but it looks like evm-lite is checking the gas and balance on a readonly operation.

**Comment by alphaqiu** [comment]
It works correctly. 

I think it should be added a param gasPrice in poa nominee command better than invoke config set before executing that command to change gasPrice.

evmlc$ c s
? Host 10.37.8.5
? Port 8080
? From 31fa29177ba613b7a3294a2a4091abf05148dce5
? Gas 1000000
? Gas Price 1
[connection]
host = "10.37.8.5"
port = 8080

[defaults]
from = "31fa29177ba613b7a3294a2a4091abf05148dce5"
gas = 1000000
gasPrice = 1
Configuration saved

evmlc$ p n
? From:  31fa29177ba613b7a3294a2a4091abf05148dce5
? Passphrase:  [hidden]
? Nominee:  0x8a8eade219c8e6a7a813c488e76937d0bf84d5d6
? Moniker:  node1
You (0x31fa29177ba613b7a3294a2a4091abf05148dce5) nominated 'node1' (0x8a8eade219c8e6a7a813c488e76937d0bf84d5d6)
evmlc$ poa whitelist
insufficient balance to pay for gas

evmlc$ c s
? Host 10.37.8.5
? Port 8080
? From 31fa29177ba613b7a3294a2a4091abf05148dce5
? Gas 1000000
? Gas Price 0
[connection]
host = "10.37.8.5"
port = 8080

[defaults]
from = "31fa29177ba613b7a3294a2a4091abf05148dce5"
gas = 1000000
gasPrice = 0
Configuration saved
evmlc$ poa whitelist
.
 |
-|
'
