### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alphaqiu** [mosaicnetworks/monetd#6]
**Expected behaviour**
After restart monetd, it can be run succefully.

**Actual behaviour**
DEBU[0000] Node does not belong to PeerSet => Joining    this_id=581936325
DEBU[0000] Run loop                                      state=Joining this_id=581936325
DEBU[0000] JOINING                                       this_id=581936325
DEBU[0000] Babble Service serving                        bind_address=":8000"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x458ea31]

goroutine 1 [running]:
github.com/mosaicnetworks/babble/src/node.(*Node).join(0xc0000d21e0, 0xc0029e5b00, 0x1)
	/Users/alpha/.../mosaicnetworks/babble/src/node/node.go:600 +0xe1
github.com/mosaicnetworks/babble/src/node.(*Node).Run(0xc0000d21e0, 0x4b44601)
	/Users/alpha/.../mosaicnetworks/babble/src/node/node.go:149 +0x213
github.com/mosaicnetworks/babble/src/babble.(*Babble).Run(0xc0002605f0)
	/Users/alpha/.../mosaicnetworks/babble/src/babble/babble.go:81 +0x3d
github.com/mosaicnetworks/evm-lite/src/consensus/babble.(*InmemBabble).Run(0xc000201bf0, 0x4b44678, 0xc000230120)
	/Users/alpha/.../mosaicnetworks/evm-lite/src/consensus/babble/babble.go:57 +0x2f
github.com/mosaicnetworks/evm-lite/src/engine.(*Engine).Run(0xc003057500, 0x14, 0xc0001a1740)
	/Users/alpha/.../mosaicnetworks/evm-lite/src/engine/engine.go:63 +0x5a
github.com/mosaicnetworks/monetd/cmd/monetd/commands.runBabble(0xc0000f3900, 0xc00018b800, 0x0, 0x2, 0x0, 0x0)
	/Users/alpha/.../mosaicnetworks/monetd/cmd/monetd/commands/run.go:78 +0x20e
github.com/spf13/cobra.(*Command).execute(0xc0000f3900, 0xc0000200a0, 0x2, 0x2, 0xc0000f3900, 0xc0000200a0)
	/Users/alpha/.../spf13/cobra/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x529da80, 0x47e07de, 0xc0001d3f88, 0xc000096058)
	/Users/alpha/.../spf13/cobra/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/alpha/.../spf13/cobra/command.go:800
main.main()
	/Users/alpha/.../mosaicnetworks/monetd/cmd/monetd/main.go:31 +0x2e

**Comment by arrivets** [comment]
I'm on it.

**Comment by alphaqiu** [comment]
Here is my peer.json file:
`➜ cat babble/peers.json|jq`
```json
[
  {
    "NetAddr": "10.37.8.5:10337",
    "PubKeyHex": "04662cb444edd523a56d2348d6692b50ad6635b03e270427aa0f75cadf04acd3a586da030c7b94aeddaaeee4c5c6a2868c94af2f5776a33455c0a8caf6592d58d4",
    "Moniker": "node0"
  }
]
```
According to the monetd documentation I tried to join a new node m1. After the new node successfully joins, the new node is stopped. At this point, node m0 will report an error. After the original node m0 is also stopped, starting m0 again will report the above null pointer error. I think the reason is that Babble's initialization order and processing logic are incorrect.
```go
// Init initialises the babble engine
func (b *Babble) Init() error {

	if err := b.initPeers(); err != nil {
		b.Config.Logger.WithError(err).Error("babble.go:Init() initPeers")
		return err
	}

	if err := b.initStore(); err != nil {
		b.Config.Logger.WithError(err).Error("babble.go:Init() initStore")
		return err
	}
```

initPeer should be initialized later than initStore. At the same time, after generating the Genesis block, the node should save the relevant information in the storage. At the next initialization, it should judge whether there is relevant data in the storage. If it exists, it should be obtained from the storage instead of getting it from `peer.json` every time. . Since the above example `peer.json` only configures one node and the node is itself, it causes the **peer** to be nil when selecting the node Join.
https://github.com/mosaicnetworks/babble/blob/c85f1c4629202ddfc567ed78c85987bb349114a0/src/node/node.go#L600

**Comment by arrivets** [comment]
The problem is that when m0 leaves, it actually removes itself from the validator-set, and saves the resulting **empty** validator-set in the database. When m0 is started again, it fetches the emtpy validator-set from the database, and Babble throws an exception when trying to select the peer to join from.

So I am fixing the issue by preventing a node from creating an InternalTransaction to leave when it is alone in the validator-set. https://github.com/mosaicnetworks/babble/commit/011e62289f86cf6797f0d28b32c2612d842d9462
That way the validator-set is never empty.

The bootstrap process is responsible for loading the validator-set from the store after it is initialised. I think it is necessary for the bootstrap process to happen after initPeers because in normal cases the validator-set from the database will correspond to the latest known validator-set, and will be more up-to-date than what initPeers() produces (based on peers.json or peers.genesis.json)
